export { ParserRegistry } from './parsers/parser-registry.js';
export { PhpParser } from './parsers/php/php-parser.js';
export { TypeScriptParser } from './parsers/typescript/typescript-parser.js';
export { AnalysisPipeline, type PipelineOptions, type ProgressEvent } from './pipeline/analysis-pipeline.js';
export { discoverFiles, type DiscoveredFile } from './pipeline/file-discovery.js';
export { detectChanges, type ChangeSet, type FileChange } from './pipeline/change-detector.js';
export { resolveReferences, type SymbolIndex, type ResolvedReference, type ResolutionResult } from './pipeline/reference-resolver.js';
export { buildHierarchy, type HierarchyResult } from './pipeline/hierarchy-builder.js';
export { aggregateEdges } from './pipeline/edge-aggregator.js';
export { getStalenessReport, type StalenessReport, type StaleNodeInfo } from './pipeline/staleness-reporter.js';
export { cascadeInvalidation, type InvalidationResult } from './pipeline/cascade-invalidator.js';
export { searchSymbols, findReferences, findDependencies, findDependents } from './query/graph-queries.js';
export type { ReferenceResult, DependencyResult, DependentResult } from './query/graph-queries.js';
export { findChildren, type ChildrenResult } from './query/children-query.js';
export { computeBlastRadius, type BlastRadiusResult, type BlastRadiusNode } from './query/blast-radius.js';
export { detectCycles } from './query/cycle-detector.js';
export { traceFlow, type TraceFlowOptions, type TraceFlowResult } from './query/trace-flow.js';
export { detectWorkspaces, type WorkspaceInfo, type WorkspacePackage } from './pipeline/workspace-detector.js';
